### ISSUE TITLE
Post-command for gap over the distribution

### ISSUE THREAD

**Issue by mhamjediers** [mhamjediers/nopo_decomposition#8]

**Comment by maximilian-sprengholz** [comment]
First setup done, can be tested with `test.do`. General question:

I think it would be best to have a standard plot in a basic style and an exported dataset which can then be used to plot in whichever style they like. Otherwise it will become very flimsy and error prone to pass on all the options to the single plots. On the other hand, I am not so sure how easy the data export would be for the da/db contribution plots (in essence, the plotting in exactly the style of WOX would necessitate additional instructions then). What do you think?

**Comment by maximilian-sprengholz** [comment]
Ready for testing as `nopo gapoverdist'

**Comment by maximilian-sprengholz** [comment]
Regarding the plotoptions, I suggest that we just return the default contents so that users can post the full set with their adjustments (similar to the `kmatch_cmdline`).

**Comment by maximilian-sprengholz** [comment]
Add sensible description of component sum checks:
- [ ] Display component, no. of quantiles, mean across quantiles, mean no. of obs per quantile
- [ ] Note that explains that mean across quantiles should be equal to compenents, except if some quantiles have sparse number of obs. and outliers affecting these. If so, use option `nquantiles()` to reduce the number of quantiles

**Comment by maximilian-sprengholz** [comment]
I have implemented only `xsize` and `ysize` as direct options for the plot. These should allow to resolve most scaling issues. Everything else is determined by defaults and returned in `r()`. Users can then either:
1. adjust these returns and feed them back to the plot command via, e.g. `twopts`
2. build their own plot from saved data and these returns

We could allow for many more direct options, but I think that in the end, you'll always need more than we offer, and in this case the two options allow for maximum flexibility (to be sure, the second option involves some coding and is not just copy paste).

Closing.
